name: Build LaTeX document
on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
            python-version: '3.10.6'
      - name: Install dependencies
        run: python -m pip install --upgrade pip
      - name: Install ipython3
        run: apt-get update && apt-get -y install ipython3
      - name: Set up nbgrader
        run: pip install nbgrader
      - name: Set up Jupyter Book
        run: pip install jupyter-book
      - name: nbgrader generates assignments
        run:  nbgrader generate_assignment "hoja_*" --CourseDirectory.root=./nbgrader --IncludeHeaderFooter.header=source/header.ipynb --force
      - name: Move nbgrader assignments for latex compilation
        run: cp -R nbgrader/release content/ejercicios
      - name: Compile HTML
        run: jupyter-book build --all content/
      - name: Upload HTML artifact
        uses: actions/upload-artifact@v3
        with:
            name: book.html
            path: content/html
      - name: Install Xelatex
        run: apt-get update && apt-get -y install texlive-full
      - name: Compile PDF
        run: jupyter-book build --all content/ --builder pdflatex
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v3
        with:
            name: book.pdf
            path: content/latex/book.pdf