name: Build LaTeX document
on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Set up Jupyter Book
        run: pip install programacion_python/requirements.txt

  build_latex:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Compile PDF
        uses: dante-ev/latex-action@master
        run: jupyter-book build --all programacion_python/ --builder pdflatex
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v3
        with:
            name: book.pdf
            path: programacion_python/latex/book.pdf

  build_html:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Compile HTML
        run: jupyter-book build --all programacion_python/
      - name: Upload HTML artifact
        uses: actions/upload-artifact@v3
        with:
            name: book.pdf
            path: programacion_python/html